apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: This is a demo Node.js service for testing CTC catalog import
  tags:
    - demo
    - nodejs
    - backend
  annotations:
    github.com/project-slug: your-github-user/demo-service
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: Sotatek-Thuy
  system: demo-system
  providesApis:
    - demo-service-api
  consumesApis:
    - another-service-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-service-api
  description: The API exposed by the demo service
spec:
  type: openapi
  lifecycle: experimental
  owner: user:guest
  definition:
    $text: |
      openapi: 3.0.0
      info:
        title: Demo Service API
        version: 1.0.0
      paths:
        /hello:
          get:
            summary: Returns a greeting message
            responses:
              '200':
                description: OK
